namespace DCS.Scripting;

/// <summary>
/// Builds the DCS-side Export.lua companion script that makes this bridge's telemetry/command
/// contract real. DCS's Export hooks can't block on socket accept(), so per LuaSocket's own
/// bundled Listener/Talker examples, DCS is the *server* (bind+accept) and this app is the
/// *client* that connects out — matching DcsConnection.cs, which already connects out to
/// dcsIp:dcsPort. Best-effort: DCS's Export environment exposes a different, smaller API surface
/// than the Hooks environment (mission-name/aircraft/multiplayer live in different places
/// depending on DCS version), so some telemetry fields may report "Unknown" until verified
/// against a live DCS session — same caveat as DcsTelemetryParser's contract.
/// </summary>
public static class LuaExportScriptGenerator
{
    public static string Generate(string dcsHost, int dcsPort) => $$"""
        -- DCSMcpBridgeExport.lua — generated by DCS.AIAutomator. Regenerate via Settings > DCS
        -- Integration > Deploy; do not hand-edit, changes will be overwritten on next deploy.
        local McpBridge = { host = "{{dcsHost}}", port = {{dcsPort}}, server = nil, client = nil }

        local function mcpBridgeLog(msg)
            if log then log.write("DCSMcpBridge", log.INFO, tostring(msg)) end
        end

        local function mcpBridgeEnsureSocket()
            if McpBridge.server == nil then
                local ok, socketLib = pcall(function()
                    package.path = package.path .. ";" .. lfs.currentdir() .. "\\LuaSocket\\?.lua"
                    package.cpath = package.cpath .. ";" .. lfs.currentdir() .. "\\LuaSocket\\?.dll"
                    return require("socket")
                end)
                if not ok then
                    mcpBridgeLog("failed to load LuaSocket: " .. tostring(socketLib))
                    return
                end
                local server, err = socketLib.bind(McpBridge.host, McpBridge.port)
                if not server then
                    mcpBridgeLog("failed to bind " .. McpBridge.host .. ":" .. McpBridge.port .. " - " .. tostring(err))
                    return
                end
                server:settimeout(0)
                McpBridge.server = server
            end

            if McpBridge.client == nil then
                local client = McpBridge.server:accept()
                if client then
                    client:settimeout(0)
                    client:setoption("tcp-nodelay", true)
                    McpBridge.client = client
                end
            end
        end

        local function mcpBridgeSendLine(line)
            if McpBridge.client == nil then return end
            local ok = McpBridge.client:send(line .. "\n")
            if not ok then
                McpBridge.client:close()
                McpBridge.client = nil
            end
        end

        local function mcpBridgeReadCommands()
            if McpBridge.client == nil then return end
            while true do
                local line, err = McpBridge.client:receive("*l")
                if line then
                    local fn, compileErr = loadstring(line)
                    if fn then
                        local ok, runErr = pcall(fn)
                        if not ok then mcpBridgeLog("command error: " .. tostring(runErr)) end
                    else
                        mcpBridgeLog("command parse error: " .. tostring(compileErr))
                    end
                elseif err == "closed" then
                    McpBridge.client = nil
                    break
                else
                    break -- "timeout": no more data queued this frame
                end
            end
        end

        local function mcpBridgeJsonEscape(s)
            return (tostring(s):gsub('[\\"]', '\\%0'):gsub('\n', '\\n'))
        end

        -- Best-effort telemetry: LoGetMissionInfo/LoGetSelfData are the closest Export-environment
        -- equivalents to mission/aircraft state. Multiplayer detection has no confirmed
        -- Export-environment API; net.get_server_id is a Hooks-environment call being tried here
        -- speculatively and will likely just leave "multiplayer" false until verified live.
        local function mcpBridgeBuildTelemetry()
            local missionActive, missionName, terrain, aircraft, multiplayer = false, "Unknown", "Unknown", "Unknown", false

            local ok, info = pcall(LoGetMissionInfo)
            if ok and info then
                missionActive = true
                missionName = info.missionName or missionName
                terrain = info.theatre or terrain
            end

            local ok2, self_ = pcall(LoGetSelfData)
            if ok2 and self_ then
                aircraft = self_.Name or aircraft
            end

            local ok3, serverId = pcall(function() return net.get_server_id() end)
            if ok3 and serverId then multiplayer = true end

            return string.format(
                '{"missionActive":%s,"missionName":"%s","terrain":"%s","aircraft":"%s","multiplayer":%s}',
                tostring(missionActive), mcpBridgeJsonEscape(missionName), mcpBridgeJsonEscape(terrain),
                mcpBridgeJsonEscape(aircraft), tostring(multiplayer))
        end

        -- Chain onto whatever Export.lua already defines (DCS-BIOS, DCSFlightpanels, VAICOM, etc.)
        -- instead of clobbering their hooks.
        local mcpBridgePrevStart = LuaExportStart
        function LuaExportStart()
            if mcpBridgePrevStart then mcpBridgePrevStart() end
            local ok, err = pcall(mcpBridgeEnsureSocket)
            if not ok then mcpBridgeLog("start error: " .. tostring(err)) end
        end

        local mcpBridgePrevAfterNextFrame = LuaExportAfterNextFrame
        function LuaExportAfterNextFrame()
            if mcpBridgePrevAfterNextFrame then mcpBridgePrevAfterNextFrame() end
            local ok, err = pcall(function()
                mcpBridgeEnsureSocket()
                mcpBridgeReadCommands()
                mcpBridgeSendLine(mcpBridgeBuildTelemetry())
            end)
            if not ok then mcpBridgeLog("frame error: " .. tostring(err)) end
        end

        local mcpBridgePrevStop = LuaExportStop
        function LuaExportStop()
            if McpBridge.client then McpBridge.client:close() end
            if McpBridge.server then McpBridge.server:close() end
            McpBridge.client, McpBridge.server = nil, nil
            if mcpBridgePrevStop then mcpBridgePrevStop() end
        end
        """;
}
