using System.Globalization;

namespace DCS.Scripting;

/// <summary>
/// Builds the DCS-side Hooks script (Saved Games\DCS\Scripts\Hooks) that makes this bridge's
/// telemetry/command contract real. The Hooks environment is used rather than Export.lua because
/// only it has the Sim.* API (mission name, map, DCS's own aircraft display names) — while still
/// exposing every Export call as Export.Lo* — and because it needs no edits to a user's
/// Export.lua. Hook callbacks can't block on accept(), so per LuaSocket's bundled
/// Listener/Talker examples DCS is the *server* (bind+accept, non-blocking) and this app is the
/// *client* that connects out (see DcsConnection).
/// API reference: DCS World/API/Sim_ControlAPI.md and DCS World/Scripts/Export.lua.
/// </summary>
public static class LuaHooksScriptGenerator
{
    /// <summary>Seconds between telemetry lines (~5 Hz): readable for the panel and plenty for an
    /// on-demand tool, far lighter than per-frame. Commands are still drained every frame.</summary>
    public const double TelemetryIntervalSeconds = 0.2;

    /// <summary>Seconds between heartbeats. Timed on real time, so they keep coming while paused
    /// (if DCS still runs frame callbacks then); the app's not-responding timeout is 5 s.</summary>
    public const double HeartbeatIntervalSeconds = 1;

    /// <param name="dcsLinkSecret">Shared with the app (Credential Locker); the app must send it as
    /// its first line or the script answers nothing and runs nothing. Restricted to base64url
    /// characters, since it's embedded in a Lua string literal.</param>
    public static string Generate(string dcsHost, int dcsPort, string dcsLinkSecret)
    {
        if (!Secrets.IsWellFormed(dcsLinkSecret))
        {
            throw new ArgumentException("The DCS link secret must be non-empty base64url ([A-Za-z0-9_-]).", nameof(dcsLinkSecret));
        }
        return Script(dcsHost, dcsPort, dcsLinkSecret);
    }

    private static string Script(string dcsHost, int dcsPort, string dcsLinkSecret) => $$"""
        -- DCSMcpBridgeHooks.lua — generated by DCS.AIAutomator. Regenerate via Settings > DCS
        -- Integration > Deploy; do not hand-edit, changes will be overwritten on next deploy.
        -- Loaded once at DCS startup (Hooks/GUI environment); restart DCS after redeploying.
        local Sim = Sim or DCS -- same API; newer DCS names it Sim.*, older versions DCS.*
        local TELEMETRY_INTERVAL = {{TelemetryIntervalSeconds.ToString(CultureInfo.InvariantCulture)}} -- seconds between telemetry lines
        local HEARTBEAT_INTERVAL = {{HeartbeatIntervalSeconds.ToString(CultureInfo.InvariantCulture)}} -- seconds between heartbeats (real time)
        local LINK_SECRET = "{{dcsLinkSecret}}" -- the app's first line must be "AUTH <secret>"
        local AUTH_TIMEOUT = 2 -- seconds a new client gets to authenticate before it's dropped
        local McpBridge = {
            host = "{{dcsHost}}", port = {{dcsPort}}, server = nil, client = nil,
            authenticated = false, clientSince = nil,
            missionName = "Unknown", terrain = "Unknown", displayNames = {}, lastSent = -1, lastHeartbeat = -1,
            logBuffer = {}, logLastSent = {}, logLastSentCount = 0,
        }
        local LOG_REPEAT_INTERVAL = 10 -- seconds: the same log message is forwarded to the app at most this often
        local LOG_BUFFER_SIZE = 10 -- log messages held while no app is connected, sent once it connects

        -- JSON string escaping, including control characters (Lua error text can carry tabs/newlines).
        local function mcpBridgeJsonEscape(s)
            return (tostring(s):gsub('[\\"]', '\\%0'):gsub('%c', function(c) return string.format('\\u%04x', c:byte()) end))
        end

        -- Wall-clock seconds (keeps running while paused), or nil if unavailable. Defined up here
        -- because Lua locals are only visible below their definition.
        local function mcpBridgeRealTime()
            local ok, t = pcall(function() return Sim.getRealTime() end)
            if ok and type(t) == "number" then return t end
            return nil
        end

        -- Writes to dcs.log and forwards to the app's log ({"log":...}); errors also become an app
        -- notification. Repeats of a message (e.g. a per-frame error) are rate-limited.
        local function mcpBridgeLog(level, msg)
            msg = tostring(msg)
            if log then log.write("DCSMcpBridge", level == "error" and log.ERROR or log.INFO, msg) end

            local now = mcpBridgeRealTime()
            if now then
                local last = McpBridge.logLastSent[msg]
                if last and now - last < LOG_REPEAT_INTERVAL then return end
                if McpBridge.logLastSentCount > 200 then McpBridge.logLastSent, McpBridge.logLastSentCount = {}, 0 end
                if last == nil then McpBridge.logLastSentCount = McpBridge.logLastSentCount + 1 end
                McpBridge.logLastSent[msg] = now
            end

            -- (final brace appended separately: two adjacent closing braces would end an
            -- interpolation hole in the C# $$ raw string this script is generated from)
            local line = string.format('{"log":{"level":"%s","message":"%s"}', level, mcpBridgeJsonEscape(msg)) .. "}"
            if McpBridge.client and McpBridge.authenticated then
                pcall(function() McpBridge.client:send(line .. "\n") end)
            else
                -- held until an authenticated app connects; never sent to an unauthenticated client
                table.insert(McpBridge.logBuffer, line)
                if #McpBridge.logBuffer > LOG_BUFFER_SIZE then table.remove(McpBridge.logBuffer, 1) end
            end
        end

        local function mcpBridgeFlushLogBuffer()
            for _, line in ipairs(McpBridge.logBuffer) do
                pcall(function() McpBridge.client:send(line .. "\n") end)
            end
            McpBridge.logBuffer = {}
        end

        local function mcpBridgeEnsureSocket()
            if McpBridge.server == nil then
                local ok, socketLib = pcall(function()
                    package.path = package.path .. ";" .. lfs.currentdir() .. "\\LuaSocket\\?.lua"
                    package.cpath = package.cpath .. ";" .. lfs.currentdir() .. "\\LuaSocket\\?.dll"
                    return require("socket")
                end)
                if not ok then
                    mcpBridgeLog("error", "failed to load LuaSocket: " .. tostring(socketLib))
                    return
                end
                local server, err = socketLib.bind(McpBridge.host, McpBridge.port)
                if not server then
                    mcpBridgeLog("error", "failed to bind " .. McpBridge.host .. ":" .. McpBridge.port .. " - " .. tostring(err))
                    return
                end
                server:settimeout(0)
                McpBridge.server = server
            end

            if McpBridge.client == nil then
                local client = McpBridge.server:accept()
                if client then
                    client:settimeout(0)
                    client:setoption("tcp-nodelay", true)
                    McpBridge.client = client
                    McpBridge.authenticated = false -- nothing runs or is sent until the AUTH line matches
                    McpBridge.clientSince = mcpBridgeRealTime()
                end
            end
        end

        local function mcpBridgeDropClient()
            if McpBridge.client then pcall(function() McpBridge.client:close() end) end
            McpBridge.client, McpBridge.authenticated, McpBridge.clientSince = nil, false, nil
        end

        -- Unguarded send, only for the handshake replies themselves.
        local function mcpBridgeSendRaw(line)
            if McpBridge.client then pcall(function() McpBridge.client:send(line .. "\n") end) end
        end

        local function mcpBridgeSendLine(line)
            if McpBridge.client == nil then return end
            if not McpBridge.authenticated then return end
            local ok = McpBridge.client:send(line .. "\n")
            if not ok then mcpBridgeDropClient() end
        end

        -- A client that hasn't authenticated within AUTH_TIMEOUT is dropped, so a stray local
        -- process can't hold the single client slot and lock the app out.
        local function mcpBridgeDropUnauthenticatedClient()
            if McpBridge.client == nil or McpBridge.authenticated or McpBridge.clientSince == nil then return end
            local now = mcpBridgeRealTime()
            if type(now) == "number" and now - McpBridge.clientSince > AUTH_TIMEOUT then
                mcpBridgeDropClient()
            end
        end

        local function mcpBridgeReadCommands()
            if McpBridge.client == nil then return end
            while true do
                local line, err = McpBridge.client:receive("*l")
                if line and not McpBridge.authenticated then
                    -- The first line must be the app's secret; nothing else is executed or answered.
                    if line == "AUTH " .. LINK_SECRET then
                        McpBridge.authenticated = true
                        mcpBridgeSendRaw('{"authOk":true}')
                        mcpBridgeFlushLogBuffer()
                    else
                        mcpBridgeSendRaw('{"authError":true}')
                        mcpBridgeDropClient()
                        mcpBridgeLog("error", "rejected a connection with a wrong link secret") -- never log the line itself
                        break
                    end
                elseif line then
                    local fn, compileErr = loadstring(line)
                    if fn then
                        local ok, runErr = pcall(fn)
                        if not ok then mcpBridgeLog("error", "command error: " .. tostring(runErr)) end
                    else
                        mcpBridgeLog("error", "command parse error: " .. tostring(compileErr))
                    end
                elseif err == "closed" then
                    mcpBridgeDropClient()
                    break
                else
                    break -- "timeout": no more data queued this frame
                end
            end
        end

        -- Mission name and map don't change during a mission, so read them once at start.
        local function mcpBridgeCacheMission()
            McpBridge.missionName, McpBridge.terrain = "Unknown", "Unknown"
            local okName, name = pcall(function() return Sim.getMissionName() end)
            if okName and name and name ~= "" then McpBridge.missionName = name end
            local okMission, mission = pcall(function() return Sim.getCurrentMission() end)
            if okMission and mission and mission.mission and mission.mission.theatre then
                McpBridge.terrain = mission.mission.theatre
            end
        end

        -- The value of an Export/Sim call, or nil if it's missing or errors.
        local function mcpBridgeCall(fn)
            local ok, value = pcall(fn)
            if ok then return value end
            return nil
        end

        local function mcpBridgeNum(v, fmt)
            if type(v) == "number" and v == v and v ~= math.huge and v ~= -math.huge then
                return string.format(fmt, v)
            end
            return "null"
        end

        -- DCS's database display name for an aircraft type (e.g. "FA-18C_hornet" -> "F/A-18C"),
        -- cached per type.
        local function mcpBridgeDisplayName(typeName)
            local display = McpBridge.displayNames[typeName]
            if display == nil then
                local name = mcpBridgeCall(function() return Sim.getUnitTypeAttribute(typeName, "DisplayName") end)
                display = (type(name) == "string" and name ~= "") and name or typeName
                McpBridge.displayNames[typeName] = display
            end
            return display
        end

        -- LoGetMCPState flags that mean something is wrong; its plain state flags are left out.
        local mcpBridgeFailureFlags = {
            "LeftEngineFailure", "RightEngineFailure", "HydraulicsFailure", "ACSFailure",
            "AutopilotFailure", "MasterWarning", "LeftTailPlaneFailure", "RightTailPlaneFailure",
            "LeftAileronFailure", "RightAileronFailure", "CannonFailure", "StallSignalization",
            "LeftMainPumpFailure", "RightMainPumpFailure", "LeftWingPumpFailure", "RightWingPumpFailure",
            "RadarFailure", "EOSFailure", "MLWSFailure", "RWSFailure", "ECMFailure", "GearFailure",
            "MFDFailure", "HUDFailure", "HelmetFailure", "FuelTankDamage",
        }

        -- LoGetMCPState only reflects the simplified FC3 flight models. Full-fidelity modules don't
        -- set these flags (verified live: an F/A-18C with engine/MC/generator failures reported
        -- none), so for them failures are "not reported" (null), never a false "none" ([]).
        local mcpBridgeFc3Types = {
            ["A-10A"] = true, ["F-15C"] = true, ["J-11A"] = true, ["MiG-29A"] = true,
            ["MiG-29G"] = true, ["MiG-29S"] = true, ["Su-25"] = true, ["Su-25T"] = true,
            ["Su-27"] = true, ["Su-33"] = true,
        }

        -- JSON array of active failure flags, or null when this aircraft doesn't report them.
        local function mcpBridgeFailuresJson(typeName)
            if not mcpBridgeFc3Types[typeName] then return "null" end
            local state = mcpBridgeCall(function() return Export.LoGetMCPState() end)
            if type(state) ~= "table" then return "null" end
            local active = {}
            for _, flag in ipairs(mcpBridgeFailureFlags) do
                local v = state[flag]
                if v == true or (type(v) == "number" and v ~= 0) then
                    active[#active + 1] = '"' .. flag .. '"'
                end
            end
            return "[" .. table.concat(active, ",") .. "]"
        end

        -- Ownship state in DCS's SI units (m, m/s, rad); conversion happens in the app.
        local function mcpBridgeOwnshipJson(self_)
            local pos = self_.LatLongAlt or {}
            return string.format(
                '{"lat":%s,"lon":%s,"altMsl":%s,"altAgl":%s,"ias":%s,"tas":%s,"mach":%s,"vs":%s,"hdg":%s,"failures":%s}',
                mcpBridgeNum(pos.Lat, "%.6f"), mcpBridgeNum(pos.Long, "%.6f"),
                mcpBridgeNum(mcpBridgeCall(function() return Export.LoGetAltitudeAboveSeaLevel() end), "%.1f"),
                mcpBridgeNum(mcpBridgeCall(function() return Export.LoGetAltitudeAboveGroundLevel() end), "%.1f"),
                mcpBridgeNum(mcpBridgeCall(function() return Export.LoGetIndicatedAirSpeed() end), "%.2f"),
                mcpBridgeNum(mcpBridgeCall(function() return Export.LoGetTrueAirSpeed() end), "%.2f"),
                mcpBridgeNum(mcpBridgeCall(function() return Export.LoGetMachNumber() end), "%.3f"),
                mcpBridgeNum(mcpBridgeCall(function() return Export.LoGetVerticalVelocity() end), "%.2f"),
                mcpBridgeNum(mcpBridgeCall(function() return Export.LoGetMagneticYaw() end), "%.4f"),
                mcpBridgeFailuresJson(self_.Name))
        end

        -- "ownship" is omitted when there's no player aircraft (spectator, dead).
        local function mcpBridgeBuildTelemetry()
            local self_ = mcpBridgeCall(function() return Export.LoGetSelfData() end)
            local aircraft, ownship = "Unknown", ""
            if type(self_) == "table" and self_.Name then
                aircraft = mcpBridgeDisplayName(self_.Name)
                ownship = ',"ownship":' .. mcpBridgeOwnshipJson(self_)
            end
            return string.format(
                '{"missionActive":true,"missionName":"%s","terrain":"%s","aircraft":"%s"%s}',
                mcpBridgeJsonEscape(McpBridge.missionName), mcpBridgeJsonEscape(McpBridge.terrain),
                mcpBridgeJsonEscape(aircraft), ownship)
        end

        -- Keep-alive for the app's not-responding watchdog. Real (wall-clock) time, not model
        -- time, which freezes while paused.
        local function mcpBridgeSendHeartbeat()
            local now = mcpBridgeRealTime()
            if type(now) ~= "number" then return end
            if now < McpBridge.lastHeartbeat or now - McpBridge.lastHeartbeat >= HEARTBEAT_INTERVAL then
                McpBridge.lastHeartbeat = now
                mcpBridgeSendLine('{"heartbeat":true}')
            end
        end

        local mcpBridgeCallbacks = {}

        function mcpBridgeCallbacks.onSimulationStart()
            McpBridge.lastSent, McpBridge.lastHeartbeat = -1, -1
            local ok, err = pcall(mcpBridgeCacheMission)
            if not ok then mcpBridgeLog("error", "start error: " .. tostring(err)) end
        end

        function mcpBridgeCallbacks.onSimulationFrame()
            local ok, err = pcall(function()
                mcpBridgeEnsureSocket()
                mcpBridgeReadCommands() -- every frame, so command latency isn't tied to the throttle
                mcpBridgeDropUnauthenticatedClient()
                if McpBridge.client == nil or not McpBridge.authenticated then return end
                mcpBridgeSendHeartbeat()
                -- Model time (pauses with the sim, restarts per mission); without it, send every frame.
                local now = mcpBridgeCall(function() return Export.LoGetModelTime() end)
                if type(now) ~= "number" or now < McpBridge.lastSent or now - McpBridge.lastSent >= TELEMETRY_INTERVAL then
                    McpBridge.lastSent = type(now) == "number" and now or -1
                    mcpBridgeSendLine(mcpBridgeBuildTelemetry())
                end
            end)
            if not ok then mcpBridgeLog("error", "frame error: " .. tostring(err)) end
        end

        -- The socket stays open between missions (this script lives as long as DCS does); just
        -- tell the app the mission ended so it clears the readout.
        function mcpBridgeCallbacks.onSimulationStop()
            pcall(mcpBridgeSendLine, '{"missionActive":false}')
        end

        -- Lets the app show PAUSED and stop expecting heartbeats (frame callbacks may stop too).
        function mcpBridgeCallbacks.onSimulationPause()
            pcall(mcpBridgeSendLine, '{"paused":true}')
        end

        function mcpBridgeCallbacks.onSimulationResume()
            pcall(mcpBridgeSendLine, '{"paused":false}')
        end

        Sim.setUserCallbacks(mcpBridgeCallbacks)
        mcpBridgeLog("info", "hooks loaded, will listen on " .. McpBridge.host .. ":" .. McpBridge.port)
        """;
}
