namespace DCS.Scripting;

/// <summary>
/// Builds the DCS-side Hooks script (Saved Games\DCS\Scripts\Hooks) that makes this bridge's
/// telemetry/command contract real. The Hooks environment is used rather than Export.lua because
/// only it has the Sim.* API (mission name, map, DCS's own aircraft display names) — while still
/// exposing every Export call as Export.Lo* — and because it needs no edits to a user's
/// Export.lua. Hook callbacks can't block on accept(), so per LuaSocket's bundled
/// Listener/Talker examples DCS is the *server* (bind+accept, non-blocking) and this app is the
/// *client* that connects out (see DcsConnection).
/// API reference: DCS World/API/Sim_ControlAPI.md and DCS World/Scripts/Export.lua.
/// </summary>
public static class LuaHooksScriptGenerator
{
    public static string Generate(string dcsHost, int dcsPort) => $$"""
        -- DCSMcpBridgeHooks.lua — generated by DCS.AIAutomator. Regenerate via Settings > DCS
        -- Integration > Deploy; do not hand-edit, changes will be overwritten on next deploy.
        -- Loaded once at DCS startup (Hooks/GUI environment); restart DCS after redeploying.
        local Sim = Sim or DCS -- same API; newer DCS names it Sim.*, older versions DCS.*
        local McpBridge = {
            host = "{{dcsHost}}", port = {{dcsPort}}, server = nil, client = nil,
            missionName = "Unknown", terrain = "Unknown", displayNames = {},
        }

        local function mcpBridgeLog(msg)
            if log then log.write("DCSMcpBridge", log.INFO, tostring(msg)) end
        end

        local function mcpBridgeEnsureSocket()
            if McpBridge.server == nil then
                local ok, socketLib = pcall(function()
                    package.path = package.path .. ";" .. lfs.currentdir() .. "\\LuaSocket\\?.lua"
                    package.cpath = package.cpath .. ";" .. lfs.currentdir() .. "\\LuaSocket\\?.dll"
                    return require("socket")
                end)
                if not ok then
                    mcpBridgeLog("failed to load LuaSocket: " .. tostring(socketLib))
                    return
                end
                local server, err = socketLib.bind(McpBridge.host, McpBridge.port)
                if not server then
                    mcpBridgeLog("failed to bind " .. McpBridge.host .. ":" .. McpBridge.port .. " - " .. tostring(err))
                    return
                end
                server:settimeout(0)
                McpBridge.server = server
            end

            if McpBridge.client == nil then
                local client = McpBridge.server:accept()
                if client then
                    client:settimeout(0)
                    client:setoption("tcp-nodelay", true)
                    McpBridge.client = client
                end
            end
        end

        local function mcpBridgeSendLine(line)
            if McpBridge.client == nil then return end
            local ok = McpBridge.client:send(line .. "\n")
            if not ok then
                McpBridge.client:close()
                McpBridge.client = nil
            end
        end

        local function mcpBridgeReadCommands()
            if McpBridge.client == nil then return end
            while true do
                local line, err = McpBridge.client:receive("*l")
                if line then
                    local fn, compileErr = loadstring(line)
                    if fn then
                        local ok, runErr = pcall(fn)
                        if not ok then mcpBridgeLog("command error: " .. tostring(runErr)) end
                    else
                        mcpBridgeLog("command parse error: " .. tostring(compileErr))
                    end
                elseif err == "closed" then
                    McpBridge.client = nil
                    break
                else
                    break -- "timeout": no more data queued this frame
                end
            end
        end

        local function mcpBridgeJsonEscape(s)
            return (tostring(s):gsub('[\\"]', '\\%0'):gsub('\n', '\\n'))
        end

        -- Mission name and map don't change during a mission, so read them once at start.
        local function mcpBridgeCacheMission()
            McpBridge.missionName, McpBridge.terrain = "Unknown", "Unknown"
            local okName, name = pcall(function() return Sim.getMissionName() end)
            if okName and name and name ~= "" then McpBridge.missionName = name end
            local okMission, mission = pcall(function() return Sim.getCurrentMission() end)
            if okMission and mission and mission.mission and mission.mission.theatre then
                McpBridge.terrain = mission.mission.theatre
            end
        end

        -- DCS's database display name for the player's aircraft type (e.g. "FA-18C_hornet" ->
        -- "F/A-18C"), cached per type. nil when there's no player aircraft (spectator, dead).
        local function mcpBridgeAircraftName()
            local ok, self_ = pcall(function() return Export.LoGetSelfData() end)
            if not ok or not self_ or not self_.Name then return nil end
            local typeName = self_.Name
            local display = McpBridge.displayNames[typeName]
            if display == nil then
                local okDisplay, name = pcall(function() return Sim.getUnitTypeAttribute(typeName, "DisplayName") end)
                display = (okDisplay and name and name ~= "") and name or typeName
                McpBridge.displayNames[typeName] = display
            end
            return display
        end

        local function mcpBridgeBuildTelemetry()
            return string.format(
                '{"missionActive":true,"missionName":"%s","terrain":"%s","aircraft":"%s"}',
                mcpBridgeJsonEscape(McpBridge.missionName), mcpBridgeJsonEscape(McpBridge.terrain),
                mcpBridgeJsonEscape(mcpBridgeAircraftName() or "Unknown"))
        end

        local mcpBridgeCallbacks = {}

        function mcpBridgeCallbacks.onSimulationStart()
            local ok, err = pcall(mcpBridgeCacheMission)
            if not ok then mcpBridgeLog("start error: " .. tostring(err)) end
        end

        function mcpBridgeCallbacks.onSimulationFrame()
            local ok, err = pcall(function()
                mcpBridgeEnsureSocket()
                mcpBridgeReadCommands()
                mcpBridgeSendLine(mcpBridgeBuildTelemetry())
            end)
            if not ok then mcpBridgeLog("frame error: " .. tostring(err)) end
        end

        -- The socket stays open between missions (this script lives as long as DCS does); just
        -- tell the app the mission ended so it clears the readout.
        function mcpBridgeCallbacks.onSimulationStop()
            pcall(mcpBridgeSendLine, '{"missionActive":false}')
        end

        Sim.setUserCallbacks(mcpBridgeCallbacks)
        mcpBridgeLog("hooks loaded, will listen on " .. McpBridge.host .. ":" .. McpBridge.port)
        """;
}
