<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="DCS.AIAutomator.Core" />
    <Using Include="DCS.AIAutomator.Mcp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DCS.AIAutomator.Mcp\DCS.AIAutomator.Mcp.csproj" />
  </ItemGroup>

</Project>